all: run clean

run: str_compare 
	 str_compare 
	

ex1: str_compare.c
	cc -E str_compare.c > str_compare-E.c
	cc -o str_compare str_compare.c

run: str_compare 
	 str_compare 
clean: 
	rm -f str_compare str_compare-E.c
	



